/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainersRouteImport } from './routes/trainers'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrainerIndexRouteImport } from './routes/trainer.index'
import { Route as ClientIndexRouteImport } from './routes/client.index'
import { Route as TrainerPlansRouteImport } from './routes/trainer.plans'
import { Route as TrainerExercisesRouteImport } from './routes/trainer.exercises'
import { Route as TrainerClientsRouteImport } from './routes/trainer.clients'
import { Route as ClientProfileRouteImport } from './routes/client.profile'
import { Route as ClientHistoryRouteImport } from './routes/client.history'
import { Route as AdminTrainersRouteImport } from './routes/admin.trainers'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'
import { Route as TrainerPlansIndexRouteImport } from './routes/trainer.plans.index'
import { Route as TrainerExercisesIndexRouteImport } from './routes/trainer.exercises.index'
import { Route as TrainerPlansPlanIdRouteImport } from './routes/trainer.plans.$planId'
import { Route as TrainerExercisesExerciseIdRouteImport } from './routes/trainer.exercises.$exerciseId'
import { Route as TrainerClientsClientIdRouteImport } from './routes/trainer.clients.$clientId'
import { Route as ClientSessionsSessionIdRouteImport } from './routes/client.sessions.$sessionId'
import { Route as TrainerPlansPlanIdTrainingsTrainingIdRouteImport } from './routes/trainer.plans.$planId_.trainings.$trainingId'

const TrainersRoute = TrainersRouteImport.update({
  id: '/trainers',
  path: '/trainers',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerIndexRoute = TrainerIndexRouteImport.update({
  id: '/trainer/',
  path: '/trainer/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/client/',
  path: '/client/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerPlansRoute = TrainerPlansRouteImport.update({
  id: '/trainer/plans',
  path: '/trainer/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerExercisesRoute = TrainerExercisesRouteImport.update({
  id: '/trainer/exercises',
  path: '/trainer/exercises',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerClientsRoute = TrainerClientsRouteImport.update({
  id: '/trainer/clients',
  path: '/trainer/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientProfileRoute = ClientProfileRouteImport.update({
  id: '/client/profile',
  path: '/client/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientHistoryRoute = ClientHistoryRouteImport.update({
  id: '/client/history',
  path: '/client/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTrainersRoute = AdminTrainersRouteImport.update({
  id: '/admin/trainers',
  path: '/admin/trainers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/admin/applications',
  path: '/admin/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerPlansIndexRoute = TrainerPlansIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TrainerPlansRoute,
} as any)
const TrainerExercisesIndexRoute = TrainerExercisesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TrainerExercisesRoute,
} as any)
const TrainerPlansPlanIdRoute = TrainerPlansPlanIdRouteImport.update({
  id: '/$planId',
  path: '/$planId',
  getParentRoute: () => TrainerPlansRoute,
} as any)
const TrainerExercisesExerciseIdRoute =
  TrainerExercisesExerciseIdRouteImport.update({
    id: '/$exerciseId',
    path: '/$exerciseId',
    getParentRoute: () => TrainerExercisesRoute,
  } as any)
const TrainerClientsClientIdRoute = TrainerClientsClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => TrainerClientsRoute,
} as any)
const ClientSessionsSessionIdRoute = ClientSessionsSessionIdRouteImport.update({
  id: '/client/sessions/$sessionId',
  path: '/client/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerPlansPlanIdTrainingsTrainingIdRoute =
  TrainerPlansPlanIdTrainingsTrainingIdRouteImport.update({
    id: '/$planId_/trainings/$trainingId',
    path: '/$planId/trainings/$trainingId',
    getParentRoute: () => TrainerPlansRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clients': typeof ClientsRoute
  '/pending': typeof PendingRoute
  '/trainers': typeof TrainersRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/trainers': typeof AdminTrainersRoute
  '/client/history': typeof ClientHistoryRoute
  '/client/profile': typeof ClientProfileRoute
  '/trainer/clients': typeof TrainerClientsRouteWithChildren
  '/trainer/exercises': typeof TrainerExercisesRouteWithChildren
  '/trainer/plans': typeof TrainerPlansRouteWithChildren
  '/client/': typeof ClientIndexRoute
  '/trainer/': typeof TrainerIndexRoute
  '/client/sessions/$sessionId': typeof ClientSessionsSessionIdRoute
  '/trainer/clients/$clientId': typeof TrainerClientsClientIdRoute
  '/trainer/exercises/$exerciseId': typeof TrainerExercisesExerciseIdRoute
  '/trainer/plans/$planId': typeof TrainerPlansPlanIdRoute
  '/trainer/exercises/': typeof TrainerExercisesIndexRoute
  '/trainer/plans/': typeof TrainerPlansIndexRoute
  '/trainer/plans/$planId/trainings/$trainingId': typeof TrainerPlansPlanIdTrainingsTrainingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clients': typeof ClientsRoute
  '/pending': typeof PendingRoute
  '/trainers': typeof TrainersRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/trainers': typeof AdminTrainersRoute
  '/client/history': typeof ClientHistoryRoute
  '/client/profile': typeof ClientProfileRoute
  '/trainer/clients': typeof TrainerClientsRouteWithChildren
  '/client': typeof ClientIndexRoute
  '/trainer': typeof TrainerIndexRoute
  '/client/sessions/$sessionId': typeof ClientSessionsSessionIdRoute
  '/trainer/clients/$clientId': typeof TrainerClientsClientIdRoute
  '/trainer/exercises/$exerciseId': typeof TrainerExercisesExerciseIdRoute
  '/trainer/plans/$planId': typeof TrainerPlansPlanIdRoute
  '/trainer/exercises': typeof TrainerExercisesIndexRoute
  '/trainer/plans': typeof TrainerPlansIndexRoute
  '/trainer/plans/$planId/trainings/$trainingId': typeof TrainerPlansPlanIdTrainingsTrainingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clients': typeof ClientsRoute
  '/pending': typeof PendingRoute
  '/trainers': typeof TrainersRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/trainers': typeof AdminTrainersRoute
  '/client/history': typeof ClientHistoryRoute
  '/client/profile': typeof ClientProfileRoute
  '/trainer/clients': typeof TrainerClientsRouteWithChildren
  '/trainer/exercises': typeof TrainerExercisesRouteWithChildren
  '/trainer/plans': typeof TrainerPlansRouteWithChildren
  '/client/': typeof ClientIndexRoute
  '/trainer/': typeof TrainerIndexRoute
  '/client/sessions/$sessionId': typeof ClientSessionsSessionIdRoute
  '/trainer/clients/$clientId': typeof TrainerClientsClientIdRoute
  '/trainer/exercises/$exerciseId': typeof TrainerExercisesExerciseIdRoute
  '/trainer/plans/$planId': typeof TrainerPlansPlanIdRoute
  '/trainer/exercises/': typeof TrainerExercisesIndexRoute
  '/trainer/plans/': typeof TrainerPlansIndexRoute
  '/trainer/plans/$planId_/trainings/$trainingId': typeof TrainerPlansPlanIdTrainingsTrainingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/clients'
    | '/pending'
    | '/trainers'
    | '/admin/applications'
    | '/admin/categories'
    | '/admin/trainers'
    | '/client/history'
    | '/client/profile'
    | '/trainer/clients'
    | '/trainer/exercises'
    | '/trainer/plans'
    | '/client/'
    | '/trainer/'
    | '/client/sessions/$sessionId'
    | '/trainer/clients/$clientId'
    | '/trainer/exercises/$exerciseId'
    | '/trainer/plans/$planId'
    | '/trainer/exercises/'
    | '/trainer/plans/'
    | '/trainer/plans/$planId/trainings/$trainingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/clients'
    | '/pending'
    | '/trainers'
    | '/admin/applications'
    | '/admin/categories'
    | '/admin/trainers'
    | '/client/history'
    | '/client/profile'
    | '/trainer/clients'
    | '/client'
    | '/trainer'
    | '/client/sessions/$sessionId'
    | '/trainer/clients/$clientId'
    | '/trainer/exercises/$exerciseId'
    | '/trainer/plans/$planId'
    | '/trainer/exercises'
    | '/trainer/plans'
    | '/trainer/plans/$planId/trainings/$trainingId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/clients'
    | '/pending'
    | '/trainers'
    | '/admin/applications'
    | '/admin/categories'
    | '/admin/trainers'
    | '/client/history'
    | '/client/profile'
    | '/trainer/clients'
    | '/trainer/exercises'
    | '/trainer/plans'
    | '/client/'
    | '/trainer/'
    | '/client/sessions/$sessionId'
    | '/trainer/clients/$clientId'
    | '/trainer/exercises/$exerciseId'
    | '/trainer/plans/$planId'
    | '/trainer/exercises/'
    | '/trainer/plans/'
    | '/trainer/plans/$planId_/trainings/$trainingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ClientsRoute: typeof ClientsRoute
  PendingRoute: typeof PendingRoute
  TrainersRoute: typeof TrainersRoute
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminTrainersRoute: typeof AdminTrainersRoute
  ClientHistoryRoute: typeof ClientHistoryRoute
  ClientProfileRoute: typeof ClientProfileRoute
  TrainerClientsRoute: typeof TrainerClientsRouteWithChildren
  TrainerExercisesRoute: typeof TrainerExercisesRouteWithChildren
  TrainerPlansRoute: typeof TrainerPlansRouteWithChildren
  ClientIndexRoute: typeof ClientIndexRoute
  TrainerIndexRoute: typeof TrainerIndexRoute
  ClientSessionsSessionIdRoute: typeof ClientSessionsSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trainers': {
      id: '/trainers'
      path: '/trainers'
      fullPath: '/trainers'
      preLoaderRoute: typeof TrainersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/': {
      id: '/trainer/'
      path: '/trainer'
      fullPath: '/trainer/'
      preLoaderRoute: typeof TrainerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/': {
      id: '/client/'
      path: '/client'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/plans': {
      id: '/trainer/plans'
      path: '/trainer/plans'
      fullPath: '/trainer/plans'
      preLoaderRoute: typeof TrainerPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/exercises': {
      id: '/trainer/exercises'
      path: '/trainer/exercises'
      fullPath: '/trainer/exercises'
      preLoaderRoute: typeof TrainerExercisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/clients': {
      id: '/trainer/clients'
      path: '/trainer/clients'
      fullPath: '/trainer/clients'
      preLoaderRoute: typeof TrainerClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/profile': {
      id: '/client/profile'
      path: '/client/profile'
      fullPath: '/client/profile'
      preLoaderRoute: typeof ClientProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/history': {
      id: '/client/history'
      path: '/client/history'
      fullPath: '/client/history'
      preLoaderRoute: typeof ClientHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/trainers': {
      id: '/admin/trainers'
      path: '/admin/trainers'
      fullPath: '/admin/trainers'
      preLoaderRoute: typeof AdminTrainersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/admin/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/plans/': {
      id: '/trainer/plans/'
      path: '/'
      fullPath: '/trainer/plans/'
      preLoaderRoute: typeof TrainerPlansIndexRouteImport
      parentRoute: typeof TrainerPlansRoute
    }
    '/trainer/exercises/': {
      id: '/trainer/exercises/'
      path: '/'
      fullPath: '/trainer/exercises/'
      preLoaderRoute: typeof TrainerExercisesIndexRouteImport
      parentRoute: typeof TrainerExercisesRoute
    }
    '/trainer/plans/$planId': {
      id: '/trainer/plans/$planId'
      path: '/$planId'
      fullPath: '/trainer/plans/$planId'
      preLoaderRoute: typeof TrainerPlansPlanIdRouteImport
      parentRoute: typeof TrainerPlansRoute
    }
    '/trainer/exercises/$exerciseId': {
      id: '/trainer/exercises/$exerciseId'
      path: '/$exerciseId'
      fullPath: '/trainer/exercises/$exerciseId'
      preLoaderRoute: typeof TrainerExercisesExerciseIdRouteImport
      parentRoute: typeof TrainerExercisesRoute
    }
    '/trainer/clients/$clientId': {
      id: '/trainer/clients/$clientId'
      path: '/$clientId'
      fullPath: '/trainer/clients/$clientId'
      preLoaderRoute: typeof TrainerClientsClientIdRouteImport
      parentRoute: typeof TrainerClientsRoute
    }
    '/client/sessions/$sessionId': {
      id: '/client/sessions/$sessionId'
      path: '/client/sessions/$sessionId'
      fullPath: '/client/sessions/$sessionId'
      preLoaderRoute: typeof ClientSessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/plans/$planId_/trainings/$trainingId': {
      id: '/trainer/plans/$planId_/trainings/$trainingId'
      path: '/$planId/trainings/$trainingId'
      fullPath: '/trainer/plans/$planId/trainings/$trainingId'
      preLoaderRoute: typeof TrainerPlansPlanIdTrainingsTrainingIdRouteImport
      parentRoute: typeof TrainerPlansRoute
    }
  }
}

interface TrainerClientsRouteChildren {
  TrainerClientsClientIdRoute: typeof TrainerClientsClientIdRoute
}

const TrainerClientsRouteChildren: TrainerClientsRouteChildren = {
  TrainerClientsClientIdRoute: TrainerClientsClientIdRoute,
}

const TrainerClientsRouteWithChildren = TrainerClientsRoute._addFileChildren(
  TrainerClientsRouteChildren,
)

interface TrainerExercisesRouteChildren {
  TrainerExercisesExerciseIdRoute: typeof TrainerExercisesExerciseIdRoute
  TrainerExercisesIndexRoute: typeof TrainerExercisesIndexRoute
}

const TrainerExercisesRouteChildren: TrainerExercisesRouteChildren = {
  TrainerExercisesExerciseIdRoute: TrainerExercisesExerciseIdRoute,
  TrainerExercisesIndexRoute: TrainerExercisesIndexRoute,
}

const TrainerExercisesRouteWithChildren =
  TrainerExercisesRoute._addFileChildren(TrainerExercisesRouteChildren)

interface TrainerPlansRouteChildren {
  TrainerPlansPlanIdRoute: typeof TrainerPlansPlanIdRoute
  TrainerPlansIndexRoute: typeof TrainerPlansIndexRoute
  TrainerPlansPlanIdTrainingsTrainingIdRoute: typeof TrainerPlansPlanIdTrainingsTrainingIdRoute
}

const TrainerPlansRouteChildren: TrainerPlansRouteChildren = {
  TrainerPlansPlanIdRoute: TrainerPlansPlanIdRoute,
  TrainerPlansIndexRoute: TrainerPlansIndexRoute,
  TrainerPlansPlanIdTrainingsTrainingIdRoute:
    TrainerPlansPlanIdTrainingsTrainingIdRoute,
}

const TrainerPlansRouteWithChildren = TrainerPlansRoute._addFileChildren(
  TrainerPlansRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ClientsRoute: ClientsRoute,
  PendingRoute: PendingRoute,
  TrainersRoute: TrainersRoute,
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminTrainersRoute: AdminTrainersRoute,
  ClientHistoryRoute: ClientHistoryRoute,
  ClientProfileRoute: ClientProfileRoute,
  TrainerClientsRoute: TrainerClientsRouteWithChildren,
  TrainerExercisesRoute: TrainerExercisesRouteWithChildren,
  TrainerPlansRoute: TrainerPlansRouteWithChildren,
  ClientIndexRoute: ClientIndexRoute,
  TrainerIndexRoute: TrainerIndexRoute,
  ClientSessionsSessionIdRoute: ClientSessionsSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
